"""Configuration file generation and management."""

import os
import secrets
from pathlib import Path
from typing import Dict, Optional, Tuple
from cryptography.fernet import Fernet


class ConfigGenerator:
    """Generates and manages .env configuration files."""

    def __init__(self, config_path: str = "/opt/wifi-portal/.env"):
        self.config_path = Path(config_path)

    @staticmethod
    def generate_secret_key(length: int = 32) -> str:
        """Generate a random secret key for JWT signing."""
        return secrets.token_hex(length)

    @staticmethod
    def generate_fernet_key() -> str:
        """Generate a Fernet key for encryption."""
        return Fernet.generate_key().decode()

    def generate_default_config(
        self,
        db_user: str = "wifi_portal",
        db_password: str = None,
        db_name: str = "wifi_portal",
        db_host: str = "localhost",
        db_port: int = 5432,
        redis_host: str = "localhost",
        redis_port: int = 6379,
        redis_db: int = 0,
        wifi_interface: str = "wlan0",
        wan_interface: str = "eth0",
        portal_ip: str = "192.168.4.1",
        portal_port: int = 8080,
        jwt_expire_hours: int = 24,
        auth_rate_limit: int = 5,
    ) -> Dict[str, str]:
        """Generate a complete configuration dictionary."""
        if db_password is None:
            db_password = secrets.token_urlsafe(16)

        return {
            # Security
            "SECRET_KEY": self.generate_secret_key(),
            "ENCRYPTION_KEY": self.generate_fernet_key(),

            # Database
            "DATABASE_URL": f"postgresql+asyncpg://{db_user}:{db_password}@{db_host}:{db_port}/{db_name}",

            # Redis
            "REDIS_URL": f"redis://{redis_host}:{redis_port}/{redis_db}",

            # Network
            "WIFI_INTERFACE": wifi_interface,
            "WAN_INTERFACE": wan_interface,
            "PORTAL_IP": portal_ip,
            "PORTAL_PORT": str(portal_port),

            # Session & Auth
            "JWT_EXPIRE_HOURS": str(jwt_expire_hours),
            "AUTH_RATE_LIMIT_ATTEMPTS": str(auth_rate_limit),

            # Database credentials (for setup scripts)
            "DB_USER": db_user,
            "DB_PASSWORD": db_password,
            "DB_NAME": db_name,
        }

    def write_env_file(self, config: Dict[str, str]) -> Tuple[bool, str]:
        """Write configuration to .env file."""
        try:
            # Ensure directory exists
            self.config_path.parent.mkdir(parents=True, exist_ok=True)

            # Write file
            lines = ["# WiFi Captive Portal Configuration", "# Generated by installer", ""]
            for key, value in sorted(config.items()):
                lines.append(f"{key}={value}")

            self.config_path.write_text("\n".join(lines) + "\n")

            # Set secure permissions
            os.chmod(self.config_path, 0o600)

            return True, str(self.config_path)
        except Exception as e:
            return False, str(e)

    def read_env_file(self) -> Dict[str, str]:
        """Read existing .env file."""
        config = {}
        if not self.config_path.exists():
            return config

        try:
            with open(self.config_path, "r") as f:
                for line in f:
                    line = line.strip()
                    if line and not line.startswith("#") and "=" in line:
                        key, value = line.split("=", 1)
                        config[key.strip()] = value.strip()
        except Exception:
            pass

        return config

    def update_env_file(self, updates: Dict[str, str]) -> Tuple[bool, str]:
        """Update specific values in existing .env file."""
        try:
            config = self.read_env_file()
            config.update(updates)
            return self.write_env_file(config)
        except Exception as e:
            return False, str(e)

    def config_exists(self) -> bool:
        """Check if configuration file exists."""
        return self.config_path.exists()

    def validate_config(self, config: Dict[str, str]) -> Tuple[bool, list]:
        """Validate that all required keys are present."""
        required_keys = [
            "SECRET_KEY",
            "ENCRYPTION_KEY",
            "DATABASE_URL",
            "REDIS_URL",
            "WIFI_INTERFACE",
            "WAN_INTERFACE",
            "PORTAL_IP",
            "PORTAL_PORT",
        ]

        missing = [key for key in required_keys if key not in config or not config[key]]
        return len(missing) == 0, missing
